name: Testing Web Coffee Shop
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: setup nodejs v22.22.0
      uses: actions/setup-node@v6 # testing
      with: 
        node-version: '22.22.0'
    - name: Check nodejs version
      run: node -v
    - name: Gethering Source Code
      uses: actions/setup-node@v6
    - name: Build App
      run: npm install && npm run build
    - name: Check build result
      run: ls dist/