# name: Testing Web Coffee Shop
# run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

# on: [push]

# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     permissions:
#       packages:
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v4
#       - name: Setup Node.js
#         uses: actions/setup-node@v6
#         with:
#           node-version: "22.x"
#       - name: Check Node.js version
#         run: node -v
#       - name: Install dependencies
#         run: npm install
#       - name: Build App
#         run: npm run build
#       - name: Check build result
#         run: ls dist/
#       - name: "[Setup] docker metadata"
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ghcr.io/abipasundan/koda-b6-react
#       - name: "[Docker] Login ghcr"
#         uses: docker/login-action@v3
#         with:
#             registry: ghcr.io
#             username: ${{ github.repository_owner }}
#             password: ${{ github.repository_owner }}
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3

#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           platforms: linux/amd64,linux/arm64
#           load: true
#           tags: user/app:latest

name: Server CI/CD
run-name: Build and Run server # ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: [push]

jobs:
  Build-and-Run:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.22.0"

      - name: Check Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Check build result
        run: ls dist/

      - name: "[Setup] docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/abipasundan/coffee-shop-web

      - name: "[Docker] Login ghcr"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # context: .
          # platforms: linux/amd64,linux/arm64
          # push: true
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      # - name: "[SERVER] pull images from repo"
      #   uses: appleboy/ssh-action@v1

      # - name: "[DOCKER] Build and push"
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      - name: "[SERVER] pull image from ghcr.io"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }} # port 68.183.226.223
          username: ${{ secrets.USERNAME }} # wildan
          key: ${{ secrets.KEY }} # private
          port: ${{ secrets.PORT }} # 22
          script: |
            docker pull ghcr.io/abipasundan/coffee-shop-web:latest
            docker rm -f web-wildan
            docker run -d -p 20601:80 --name web-wildan ghcr.io/abipasundan/coffee-shop-web:latest

        # with:
        #   context:
        #   host: ${{ secret.HOST }}
        #   username: ${{ secret.USERNAME }}
        #   key: ${{ secret.KEY }}
        #   port: ${{ secret.PORT }}
        #   script: |
        #     docker pull ghcr

      # - name: "[SERVER] pull images from repo"
      #   uses: appleboy/ssh-action@v1
      # with:
      #   host: ${{ secret.HOST }}
      #   username: ${{ secret.USERNAME }}
      #   key: ${{ secret.KEY }}
      #   port: ${{ secret.PORT }}
      #   script: |
      #     docker pull ghcr